//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistEstacionDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstacionServicio
    {
        public string IdEstacionServicio { get; set; }
        public string Direccion { get; set; }
        public string CodRegion { get; set; }
        public int CapacidadMax { get; set; }
        public string HorarioAtencio { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
